name:                 deflate-decompress
version:              0.1.0.0
visibility:           public
id:                   deflate-decompress-0.1.0.0-inplace
key:                  deflate-decompress-0.1.0.0-inplace
license:              MIT
maintainer:           pristalov.rm@phystech.edu
author:               Pristalov R. & Tsedenov A.
synopsis:             Educational implementation of DEFLATE decompressor.
description:
    Our implementation of DEFLATE decompressor for TIPL course at MIPT using Haskell and based on RFC 1951 memo.

category:             Codec
abi:                  inplace
exposed:              True
exposed-modules:
    Codec.Deflate Codec.Deflate.Decoder Codec.Deflate.GlobalTypes
    Data.BitStream Data.Huffman

import-dirs:
    /home/alvaro-sann/programming/haskell/deflate-decompress/dist-newstyle/build/x86_64-linux/ghc-9.6.7/deflate-decompress-0.1.0.0/build

library-dirs:
    /home/alvaro-sann/programming/haskell/deflate-decompress/dist-newstyle/build/x86_64-linux/ghc-9.6.7/deflate-decompress-0.1.0.0/build

library-dirs-static:
    /home/alvaro-sann/programming/haskell/deflate-decompress/dist-newstyle/build/x86_64-linux/ghc-9.6.7/deflate-decompress-0.1.0.0/build

dynamic-library-dirs:
    /home/alvaro-sann/programming/haskell/deflate-decompress/dist-newstyle/build/x86_64-linux/ghc-9.6.7/deflate-decompress-0.1.0.0/build

data-dir:             /home/alvaro-sann/programming/haskell/deflate-decompress/.
hs-libraries:         HSdeflate-decompress-0.1.0.0-inplace
depends:              base-4.18.3.0 bytestring-0.11.5.4 mtl-2.3.1
haddock-interfaces:
    /home/alvaro-sann/programming/haskell/deflate-decompress/dist-newstyle/build/x86_64-linux/ghc-9.6.7/deflate-decompress-0.1.0.0/doc/html/deflate-decompress/deflate-decompress.haddock

haddock-html:
    /home/alvaro-sann/programming/haskell/deflate-decompress/dist-newstyle/build/x86_64-linux/ghc-9.6.7/deflate-decompress-0.1.0.0/doc/html/deflate-decompress
